### PR TITLE
fix: image source after drag and drop

### LINKED ISSUE #1281: 🐞 -  Bug - TuiNodeViewNg- Node Conflict after dragging and dropping
### Playground Link

_No response_

### Description

https://github.com/user-attachments/assets/c4ea1bd7-1b70-4bc7-93d7-dad42021e953

The node displays the content of the first component, instead of the second after dragging it from one place to the other.
This doesn't only happen with TuiImageEditor but with any component really, so it has to do with how  TuiNodeViewNg deals with nodes.

### Angular version

latest - deployed

### Taiga UI version

v2.5.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by hakimio**
Fixes #1281

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Comment by splincode** [comment]
@hakimio awesome work
image


Could you check please it in iframe component?

**Comment by hakimio** [comment]
@splincode it works the same in iframe and normal window.
The problem with this workaround is that the image is not updated until change detection is triggered some way, ie by moving the mouse:
change-detection

Maybe we need to explicitly trigger change detection every time `attrs` is set?

**Comment by splincode** [comment]
`Maybe we need to explicitly trigger change detection every time attrs is set` 

show me example, how, please

**Comment by splincode** [comment]
@hakimio try add 

```ts
  this.notifyUpdate();
  return this.sanitizer.bypassSecurityTrustResourceUrl(src);
  ```

**Comment by hakimio** [comment]
@splincode the problem with calling `this.notifyUpdate()` in `getBypassedSrc()` is that `getBypassedSrc()` is only called when change detection is triggered. So, it doesn't do anything.

The following workaround works but I am not sure if that's the right approach here:

image

What do you think about it?

**Comment by splincode** [comment]
You can add it, why not

**Pull request merged**
